# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aabe55e4d73ca1661eadeec602b4815f87e54983ebec06f08b461b983c623ad874b1bd3f7da8db0a4780d33de5e75584c22be0c69289d6975fffada46c3c4f63

test:
  secret_key_base: 62fc9632476c0fdc7a49745907cf0805e8fae76158388dc3116965aaf3fc5b432f5a08f72793246f9c6118d5d35f1813a0e3ff275eecc78584a389094cb857ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
